name: Build ConsoleDeckService

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore .NET Packages
        run: |
          cd ConsoleDeckService
          dotnet restore
  
      - name: Run all unit tests
        run: |
          cd ConsoleDeckService
          dotnet test --no-restore
  
      - name: Build release
        run: |
          cd ConsoleDeckService
          dotnet build -o Release --no-restore

      - name: Upload build artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: console_deck_service
          path: ./ConsoleDeckService/bin/Release/net10.0/
          compression-level: 6
          overwrite: true
