name: Build the MSI Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          run-id: 20033189443
          artifact-ids: 4799089184
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install WiX Toolset
        run: choco install wixtoolset -y
      
      - name: Harvest files with Heat
        run: |
          heat.exe dir . -cg ProductComponents -dr INSTALLFOLDER -out components.wxs -scom -sreg -sfrag -srd -gg -t transform.xslt
          Get-Content components.wxs

      - name: Build MSI via WiX
        run: |
          candle.exe components.wxs -out consoledeck_service.wixobj
          light.exe consoledeck_service.wixobj -o ConsoleDeckService.msi

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v5
        with:
          name: consoledeck_service.msi
          path: ConsoleDeckService.msi
        
        
