name: Build the MSI Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Create release directory
        run: mkdir release
        
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          run-id: 20070383020
          artifact-ids: 4813251898
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./release

      - name: Move Advanced Installer to root folder
        run: Move-Item -Path ./release/ConsoleDeck_Service.aip -Destination ./ConsoleDeck_Service.aip

      - name: MSI via Advanced Installer
        uses: caphyon/advinst-github-action@main
        with:
          advinst-version: '23.3'
          advinst-enable-automation: true
          aip-path: ./ConsoleDeck_Service.aip

      - name: List files
        run: ls './ConsoleDeck_Service-SetupFiles'

      #- name: Install WiX Toolset
      #  run: choco install wixtoolset -y
      
      #- name: Harvest files with Heat
      #  run: |
      #    heat.exe dir . -cg ProductComponents -dr INSTALLFOLDER -out components.wxs -scom -sreg -sfrag -srd -gg
      #    Get-Content components.wxs        

      #- name: Build MSI via WiX
      #  run: |
      #    candle.exe consoledeck_service.wxs -out consoledeck_service.wixobj
      #    light.exe consoledeck_service.wixobj -ext WixUIExtension -o ConsoleDeckService.msi

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v5
        with:
          name: 'ConsoleDeck_Service.msi'
          path: './ConsoleDeck_Service-SetupFiles/ConsoleDeck_Service.msi'
        
        
