name: Build the MSI Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          run-id: 20029413130
          artifact-ids: 4797587316
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install go-msi
        run: choco install -y "go-msi"

      - name: Build Windows Installer MSI from exe file
        uses: AliceOh/CreateWindowsInstaller@1.0.0
        with:
          exefile: 'helloworld.exe'

      - name: Check results
        run: |
          ls

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v5
        with:
          name: consoledeck_service.msi
          path: package.msi
        
        
