name: Build ConsoleDeckService

on:
  push:
    branches: "main"

env:
  MY_WORK_DIR: ./ConsoleDeckService

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore .NET Packages
        working-directory: ${{ env.MY_WORK_DIR }}
        run: dotnet restore
  
      - name: Run all unit tests
        working-directory: ${{ env.MY_WORK_DIR }}
        run: dotnet test --no-restore
  
      - name: Build release
        working-directory: ${{ env.MY_WORK_DIR }}
        run: dotnet build --no-restore

      - name: Upload build artifact
        uses: actions/upload-artifact@v5
        with:
          name: console_deck_service
          path: ${{ env.MY_WORK_DIR }}/bin/Release/net10.0/
          compression-level: 6
          overwrite: true
